global:
  scrape_interval: 15s  # Default scrape interval for all targets.
  evaluation_interval: 15s  # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']  # Adjust if Promtail exposes metrics on a different port.

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

# Scrape application metrics
#  - job_name: "application"
#   metrics_path: "/api/metrics"  # Your application metrics endpoint
#   static_configs:
#     - targets: ["192.168.100.28:3000"]  # Replace with your application's address and port